<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [1]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    x=[]
    y=[]
    for i in range(len(A)):
        for j in range(len(B[0])):
            z=0
            for a in range(len(B)):
                z+= A[i][a] * B[a][j]
            x.append(z)
        y.append(x)
        x=[]
        
    # write your code
    return(y)

#A=[[1,2],[3,4]]
#B=[[1,2,3,4,5],[5,6,7,8,9]]
#A=[[1,3,4],[2,5,7],[5,9,6]]
#B=[[1,0,0],[0,1,0],[0,0,1]]
A=[[1,2],[3,4]]
B=[[1,4],[5,6],[7,8],[9,6]]
if(len(A)==len(B)):
    matrix_mul(A, B)
else:
    print("Multiplication not possible")


Multiplication not possible


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [2]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude
    s=0
    x=0
    #adding all element
    s=sum(A)
    li=[]
    for i in A:
        li.append(x+i)
        x=x+i
    #we have to set the upper boundary of uniform as total sum 
    #or else we have to divide cum sum by total sum so as to normalized it between (0,1)
    #and then we can set upper limit of uniform as 1
    bit=uniform(0,s)
    for i in range (0,s):
        if bit<li[i]:
            return A[i]#random num
        
def sampling_based_on_magnitued():
    final_list=[]
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        final_list.append(number)
    return(final_list)
A = [0,5,27,6,13,28,100,45,10,79]
y=sampling_based_on_magnitued()
print(y)
print("number,probability")
for i in A:
    n=y.count(i)
    prob=n/len(y)
    print(i,prob)


[79, 45, 100, 79, 45, 45, 45, 45, 45, 45, 100, 27, 45, 100, 28, 100, 79, 45, 100, 100, 28, 10, 27, 79, 28, 79, 100, 100, 100, 45, 79, 100, 13, 100, 100, 100, 79, 79, 79, 28, 79, 45, 100, 79, 100, 79, 100, 45, 13, 45, 79, 79, 79, 79, 13, 100, 28, 79, 45, 100, 100, 79, 100, 79, 79, 45, 28, 45, 27, 28, 28, 79, 100, 79, 79, 27, 45, 100, 45, 100, 45, 45, 100, 13, 45, 10, 45, 28, 100, 28, 27, 45, 100, 28, 100, 45, 10, 5, 79]
number,probability
0 0.0
5 0.010101010101010102
27 0.050505050505050504
6 0.0
13 0.04040404040404041
28 0.1111111111111111
100 0.2727272727272727
45 0.24242424242424243
10 0.030303030303030304
79 0.24242424242424243


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [3]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(String):
    c=''
    for i in range(len(String)):
        try:
            d=int(String[i])
            c=c+'#'
        except ValueError:
            continue
    # write your code
    # 
    return(c) # modified string which is after replacing the # with digits
String=input("Enter string: ")
replace_digits(String)

Enter string: asd34r


'##'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [4]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(students, marks):
    top_5_students=[]
    least_5_students=[]
    students_within_25_and_75=[]
    n=len(marks)
    n_id=n-1
    zip_stu_mks=zip(marks,students)
    new_students=[x for _,x in sorted(zip_stu_mks)]
    for i in range(5):
        least_5_students.append(new_students[i])
        top_5_students.append(new_students[n_id-i])   
    top=marks[len(marks)-1]
    up_limit=top*0.75//1
    lo_limit=top*0.25//1
    marks.sort()
    for i in range(len(marks)):
        if(marks[i]>lo_limit and marks[i]<up_limit):
            students_within_25_and_75.append(new_students[i])
    
    return top_5_students, least_5_students, students_within_25_and_75
students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 46, 98, 35, 80]
top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)
print("Name of top 5 students: ",top_5_students)
print("Name of least 5 students: ",least_5_students)
print("Name of students Who got marks between >25th percentile <75th percentile, in the increasing order of marks: ",students_within_25_and_75)

Name of top 5 students:  ['student8', 'student10', 'student2', 'student5', 'student7']
Name of least 5 students:  ['student3', 'student4', 'student9', 'student6', 'student1']
Name of students Who got marks between >25th percentile <75th percentile, in the increasing order of marks:  ['student9', 'student6', 'student1', 'student7', 'student5']


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [5]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    cos_dis=[]
    x=P[0]
    y=P[1]
    closest_points_to_p=[]
    for i in range(len(S)):
        p=S[i][0]
        q=S[i][1]
        num=(x*p)+(y*q)
        d=((x*x)+(y*y))*((p*p)+(q*q))
        den=math.sqrt(d)
        cos_dist=math.acos(num/den)
        cos_dist=round(cos_dist,4)
        cos_dis.insert(i,cos_dist)
        print(p,q,cos_dist)
    zip_points=zip(cos_dis,S)
    sort_points=[x for _,x in sorted(zip_points)]
    print()
    for i in range (5):
        closest_points_to_p.append(sort_points[i])
    return closest_points_to_p  # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print("Closest points: ",points) #print the returned values

1 2 2.0344
3 4 1.8546
-1 1 2.9997
6 -7 0.0651
0 6 2.4981
-5 -8 1.2021
-1 -1 1.4289
6 0 0.9273
1 -1 0.1419

Closest points:  [(6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1)]


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [6]:
import math
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    ct1=0
    ct2=0
    a,b,c=[float(coef.strip()) for coef in re.split('x|y', line)]
    for i in red:
        x=i[0]
        y=i[1]
        z=a*x+b*y+c
        if(z>0):
            ct1+=1
    for j in blue:
        x=i[0]
        y=i[1]
        z=a*x+b*y+c
        if(z>0):
            ct2+=1
    if(ct1==5 and ct2==5):
        return 1
    else:
        return 0

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    if(i_am_the_one(Red, Blue, i)==1):
        print("YES")
    else:
        print("NO")
    

YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [7]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(string):
    s=list(string.split(","))
    #print(s)
    n=len(s)
    z=0
    b = 0
    a = 0
    for i in range(n):
        #print(i)
        if s[i] != '_' or (i + 1 == n):
            try:
                int(s[i])
                z=int(s[i])
            except ValueError:
                z=0
            z = (z + a) / (i - b + 1)
            #print(b, i + 1)
            for j in range(b, i + 1):
                s[j] = z
                #print(j)
            a = z
            b=i
    # your code
    return s
S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
#print(# print above values)
print(smoothed_values)

[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/2, P(F=F1|S==S2)=1/2, P(F=F1|S==S3)=0/2
b. P(F=F2|S==S1)=1/3, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/3, P(F=F3|S==S2)=1/2, P(F=F3|S==S3)=1/2
d. P(F=F4|S==S1)=1/2, P(F=F4|S==S2)=0/2, P(F=F4|S==S3)=1/2
e. P(F=F5|S==S1)=1/1, P(F=F5|S==S2)=0/1, P(F=F5|S==S3)=0/1
</pre>



In [8]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings



# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    n=len(A)
    for i in range (n):
        ct=0
        for j in range(n):
            if(A[i][0]==A[j][0]):
                ct+=1
        ct2=0
        for k in range(n):
            if(A[i]==A[k]):
                ct2+=1
        print("P(F=",A[i][0],"|S==",A[i][1],")=",ct2/ct)
    # your code
    # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

P(F= F1 |S== S1 )= 0.5
P(F= F2 |S== S2 )= 0.3333333333333333
P(F= F3 |S== S3 )= 0.5
P(F= F1 |S== S2 )= 0.5
P(F= F2 |S== S3 )= 0.3333333333333333
P(F= F3 |S== S2 )= 0.5
P(F= F2 |S== S1 )= 0.3333333333333333
P(F= F4 |S== S1 )= 0.5
P(F= F4 |S== S3 )= 0.5
P(F= F5 |S== S1 )= 1.0


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [9]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    l1=list(S1.split(" "))
    l2=list(S2.split(" "))
    com=[]
    com1=[]
    ct=0
    com=l1.copy()
    com1=l2.copy()
    for i in range (len(l1)):
        try:
            com.remove(l2[i])
            ct+=1
        
        except ValueError:
            pass
    for i in range(len(l2)):
        try:
            com1.remove(l1[i])
        
        except ValueError:
            pass
    return ct,com,com1

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
#print(#the above values)
print(a,b,c)

7 ['first', 'F', '5'] ['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [10]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
import math

# you can free to change all these codes/structure
def compute_log_loss(A):
    # your code
    n=len(A)
    z=0
    for i in range(n):
        x=A[i][0]
        y=A[i][1]
        a=1-x
        b=1-y
        z=z+((x*(math.log10(y)))+(a*(math.log10(b))))
    return (-(z/8))

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
